### ISSUE TITLE
Make page margins consistent

### ISSUE THREAD

**Issue by janthoXO** [ls1intum/thesis-template-typst#38]
Currently when one wants to change the page margins, he/she would have to go in each layout file and adjust them. it would be better if they can just be adjusted in the layout/proposal or layout/thesis and are then inherited for the sub layouts

**Comment by janthoXO** [comment]
same goes for the text font and size

**Comment by robertjndw** [comment]
You can change the margin for all of the content text on your own. The other layouts specify their own margins as these are fixed and should not change easily
